#!/bin/sh

echo "** Checking format ..."
cargo fmt --check

echo "** Checking code ..."
cargo clippy --no-deps

echo "** Verifying project ..."
cargo verify-project

echo "** Building ..."
cargo build

echo "** Testing ..."
cargo test --no-fail-fast
