#!/bin/sh

rm -rf generated/coverage/data/* generated/coverage/html/*

CARGO_INCREMENTAL=0
export CARGO_INCREMENTAL
RUSTFLAGS='-Cinstrument-coverage'
export RUSTFLAGS
LLVM_PROFILE_FILE='generated/coverage/data/cargo-test-%p-%m.profraw'
export LLVM_PROFILE_FILE

env TEST=1 cargo test --no-fail-fast -- --nocapture 8080 "::"

grcov . --binary-path ./target/debug/deps/ -s . -t html \
  --branch --ignore-not-existing --ignore '../*' --ignore "/*" \
  --excl-line "grcov-excl-line|^$|#\[|mod |use |^\\W*\/\/|^\\W*\}" \
  --excl-start "grcov-excl-start" --excl-stop "grcov-excl-stop" \
  -o ./generated/coverage/
