name: CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check format
      run: cargo fmt --check

    - name: Clippy
      run: cargo clippy --no-deps

    - name: Verify
      run: cargo verify-project

    - name: Build
      run: cargo build --all-targets

    - name: Test
      run: cargo test --no-fail-fast
